### ISSUE TITLE
0-byte files cause issues

### ISSUE THREAD

**Issue by catharsis71** [kotx/render#10]
maybe this is a Cloudflare issue or something but I'll mention it here

you can definitely create 0-byte files in R2 buckets

but trying to access them through your script results in odd behavior

using a HEAD request it returns a HTTP 204 (No Content) which is sensible

however using a GET request, the browser gets a HTTP 500 (Internal Server Error) along with some HTML claiming there was an error 1101

![image](https://user-images.githubusercontent.com/70603733/172711047-e48d2abe-319f-42c9-9af7-1818a241f8d4.png)

if I test it in the worker dashboard this is what I see:

![image](https://user-images.githubusercontent.com/70603733/172711366-2b3ebe5c-0384-426f-8416-6ba3609de67a.png)

**Comment by kotx** [comment]
Ah, seems like I need to return `null` if the body is 0-length. I'll look into that now.

**Comment by kotx** [comment]
Fixed by bb394272721148205c1521255ec1e657cbf887b7, thanks!

**Comment by catharsis71** [comment]
I've been thinking about this some more

Seems like most web servers serve 0-byte files by responding with a 200 OK with a "content-length: 0".  I can't speak for every web server but that's definitely how Apache does it, as well as whatever Github Pages and Cloudflare Pages are running.

Was it a conscious decision to use a 204 No Content for this or are you just getting a 204 from R2 and passing it along?

Would it make more sense to copy how most web servers behave and do it as a 200 OK / content-length: 0?    With a 200 OK, you're able to actually browse to a 0-byte file and the browser will show a blank page (unless the server set the content type as application/octet-stream in which case it will treat it as a download), whereas with a 204 No Content, the browser will remain on the page it's on and it will basically seem like nothing happened (regardless of content-type).

**Comment by kotx** [comment]
I checked this some more and it seems like 200 is more appropriate. Also I forgot to send Content-Length it seems? I can't fix this now as I'll be busy for the next few days but if you want you can PR this, should be fairly straightforward. Sorry if it causes you any inconvenience.

**Comment by kotx** [comment]
I believe I've fixed this with c2f347b56ebd9f4cbd9c1ea798f53bc0d66d07ef. Let me know if anything else breaks.

**Comment by catharsis71** [comment]
I had to flush my cache but yeah now it's a 200  (and now I know caching really is working)
