### ISSUE TITLE
Music playing CORS/Cache/worker error

### ISSUE THREAD

**Issue by djkato** [kotx/render#13]
Whenever I try playing music on my [website](https://djkato.net/mixes), I get either  ```Failed to load resource: net::ERR_CACHE_OPERATION_NOT_SUPPORTED```

 or CORS error like 
![image](https://user-images.githubusercontent.com/25299243/186535188-f5b52668-5f91-4766-abb3-683dac93d113.png). 
Googling returned 0 results, what can I do? I've been fighting with CORS since I thought that's the issue, but this made me think CORS might not be the issue. could it be the worker?
inside the `wrangler.toml` file, I set my origins to:
```env
ALLOWED_ORIGINS = "https://djkato.net/"
```
All other files load just fine(eg videos, images). Just audio seems messed up, regardless if `crossorigin="anonymous"` is set via html property on the audio element, or before initializing the web Audio API context through `HTMLMediaElement.crossOrigin = "anonymous"`, or even not set anywhere. if I don't set it anywhere, I get "audio source set to none due to cors issues" or something along those lines.
Any tips on solving this? Thanks!

**Comment by kotx** [comment]
I opened it in Firefox and saw this error:
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cdn.djkato.net/music/Djk%C3%A1%C5%A5o%20Live%20at%20Discord%20EP%209.ogg. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘https://djkato.net/’).

I checked the network log and saw that cdn.djkato.net returns `https://djkato.net/` for the `access-control-allow-origin` header. Perhaps you need to remove the trailing slash?

**Comment by djkato** [comment]
> > Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cdn.djkato.net/music/Djk%C3%A1%C5%A5o%20Live%20at%20Discord%20EP%209.ogg. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘[https://djkato.net/’](https://djkato.net/%E2%80%99)).
> 
> I checked the network log and saw that cdn.djkato.net returns `https://djkato.net/` for the `access-control-allow-origin` header. Perhaps you need to remove the trailing slash?

This seems to have done it! after flushing browser cache the music works now too, amazing~

> Edit: Also, it seems the images on your site are loaded from djkato.net, not cdn.djkato.net. So that would explain images and videos working as you describe.

![image](https://user-images.githubusercontent.com/25299243/186541315-147c6884-0782-4a96-85fd-1e3821f6cd55.png)
Well that's weird though, I see all sources from `cdn.djkato.net`

regardless, it works now so thanks! Weird issue, would never figure that one out lol
PS: That's not zero-two is it?

**Comment by kotx** [comment]
> Well that's weird though, I see all sources from cdn.djkato.net

Ah then I might've been looking at the wrong thing, oops!

Glad you got it working regardless!

>  PS: That's not zero-two is it?

zero two is good, but nope, it's [KAF](https://www.youtube.com/c/%E8%8A%B1%E8%AD%9C)!

**Comment by djkato** [comment]
Hehe, cultured men running the world, happy to see it 🙏 KAF in cytus II best
Bless you
