### ISSUE TITLE
Cache hit ignored for 304 response

### ISSUE THREAD

**Issue by Zeblote** [kotx/render#17]
Hi, just noticed that you are checking for response.ok() to see if cache was hit. This will fail if cache returned a 304 response to a correct etag.

**Comment by kotx** [comment]
Hey, this should be a simple fix but I'm off for a few days- feel free to implement this yourself if you feel the need, I'll be happy to merge it.

**Comment by kotx** [comment]
Fixed, but only for 304 responses. LMK if you need some other status code.
