### ISSUE TITLE
Chinese characters may display as garbled text

### ISSUE THREAD

**Issue by IlluminateDarkheat** [kotx/render#29]
The possible reason is that the Chinese characters encoded in UTF-8 were read in GBK format.

An example:
搴斿鐗规畩鏃舵湡鐨勫簲鎬ョ墿璧勬竻鍗晇1.2.pdf
Actually should be:
应对特殊时期的应急物资清单v1.2.pdf

**Comment by kotx** [comment]
Is this in a file listing or in an HTML file or something else?

**Comment by IlluminateDarkheat** [comment]
> Is this in a file listing or in an HTML file or something else?

I'm not quite sure, do you mean the configuration [here](https://github.com/IlluminateDarkheat/render/blob/master/wrangler.toml)?

**Comment by kotx** [comment]
Where are you seeing that Chinese characters are garbled? Is it in a file served by render?

**Comment by IlluminateDarkheat** [comment]
On the page of Workers.
[An example](https://r2.jghg.eu.org/)

I'm not sure if render will generate a file in the R2 bucket, maybe there is something wrong with my configuration?

**Comment by kotx** [comment]
Just pushed a commit that ensures the directory listing is parsed as UTF-8, (version 1.1.3), let me know if it works.

**Comment by IlluminateDarkheat** [comment]
Everything is fine now. Thank you very much for your work!
