### ISSUE TITLE
File Not Found

### ISSUE THREAD

**Issue by hieroglyphicss** [kotx/render#33]
It will always display that the file cannot be found, and the deployment of GitHub Action has been completed. After opening the Workers page, it will display File Not Found

**Comment by Erisa** [comment]
Hi, are you able to provide an example? The Worker is bound to a bucket and won't display anything for the root path unless you enable `DIRECTORY_LISTING` in `wrangler.toml` - you will see File Not Found unless you access a specific path for a file or have dir listing enabled.

If your repository is public, are you able to share a URL to the `wrangler.toml` configuration used?

**Comment by hieroglyphicss** [comment]
Oh! Sorry, I did not notice the file directory of the file. I was very sorry to occupy your time. Your project is very good and it is very helpful to me!

**Comment by kotx** [comment]
No problem, thanks for using it!!
