### ISSUE TITLE
cache.put always fired

### ISSUE THREAD

**Issue by bl-kl2** [kotx/render#7]
Hi,
thanks for sharing this great tool.
I've a question:
is there a specific reason for having cache.put fired also when the response is already in cache (previous cache.match)?

Thanks!

**Comment by kotx** [comment]
Hi, thanks for the report!
I don't think there is a reason, I'll fix it now.

**Comment by kotx** [comment]
Fixed by 9f97dfcc37dc95d6a758660e0b625ba0ee3f95ab. Thanks!
